name: Playlist Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 2am UTC
    - cron: '2 0 * * *'

jobs:
  update-playlist:
    name: Update Playlist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "PLAYLIST"
          commit_message: "Update playlist data"
          feed_list: "https://www.youtube.com/feeds/videos.xml?playlist_id=PLud7IEoxEsoV-NA6CIIKPnTRVAgcpF5YS"
          max_post_count: 15