name: Playlist Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'

jobs:
  update-kpop:
    name: Update Playlist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "KPOP"
          commit_message: "Update K-pop playlist data"
          feed_list: "https://www.youtube.com/feeds/videos.xml?playlist_id=PLud7IEoxEsoV7X01Y2JMPA_NYthU0755G"
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "POP"
          commit_message: "Update Pop playlist data"
          feed_list: "https://www.youtube.com/feeds/videos.xml?playlist_id=PLud7IEoxEsoU8IC6tfIsG2EnhdJzLWHbd"
